name: Build and Push Docker Image to Docker Hub and ECR

on: 
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Push Docker Image to Docker Hub and ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
    # DOCKER HUB
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/man-go:latest
          context: .